### PR TITLE
Add zkcrypto support

### PR DESCRIPTION
**Pull request by Nick9707**

### CODE REVIEW

**Comment by sauliusgrigaitis** [comment]
Thanks, I checked EIP-4844, however the performance is terrible:

```
running 8 tests
test tests::bytes_to_bls_field_test_ ... ok
test tests::compute_powers_test_ ... ok
test tests::aggregate_proof_for_single_blob_test_ has been running for over 60 seconds
test tests::blob_to_kzg_commitment_test_ has been running for over 60 seconds
test tests::compute_aggregate_kzg_proof_test_empty_ has been running for over 60 seconds
test tests::compute_commitment_for_blobs_test_ has been running for over 60 seconds
test tests::eip4844_test_ has been running for over 60 seconds
test tests::evaluate_polynomial_in_evaluation_form_test_ has been running for over 60 seconds
test tests::evaluate_polynomial_in_evaluation_form_test_ ... ok
test tests::compute_aggregate_kzg_proof_test_empty_ ... ok
test tests::blob_to_kzg_commitment_test_ ... ok
test tests::aggregate_proof_for_single_blob_test_ ... ok
test tests::compute_commitment_for_blobs_test_ ... ok
test tests::eip4844_test_ ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 141.87s
```

It's not surprising `zkcrypto` that is slower, but I didn't expect that it's slower almost 50 times! Something must be wrong. Also, seems `tests::verify_aggregate_kzg_proof_test_empty_` is missing. 

Could you try to port the [benchmarks](https://github.com/sifraitech/rust-kzg/blob/main/blst-from-scratch/benches/eip_4844.rs) and get a very rough idea of why it's so insanely slow? It's normal that it's 2-3X slower according to  https://hackmd.io/@gnark/eccbench , but not that much we see in the tests.

**Comment by Nick9707** [comment]
Screenshot 2023-01-31 at 7 27 25 AM
I did the pr on the code before this merge, this is why test is not there

**Comment by belijzajac** [comment]
Cherry picked @Nick9707's commit into #199.

The reason for it for being so slow is because it was naively multiplying `G1` points by `Fr` points for `4096`  (field elements per blob) times! Replaced old logic with MSM https://github.com/sifraitech/rust-kzg/pull/199/commits/fd8852053b8233941cce6e0d9bc419492e272b65 and the performance now is reasonable.

Here are the local benchmark results without the parallel feature:

| benchmark | times slower than blst-from-scratch |
|--------|--------|
| blob_to_kzg_commitment | 3.13 (was 18.29 with old logic) |
| compute_kzg_proof | 3.06 (was 17.55 with old logic) |
| compute_blob_kzg_proof | 3.04 (was 17.72 with old logic)  |
| verify_blob_kzg_proof | 2.20 |
| verify_blob_kzg_proof_batch/1 | 2.15 |
| verify_blob_kzg_proof_batch/2 | 1.90 |
| verify_blob_kzg_proof_batch/4 | 1.65 |
| verify_blob_kzg_proof_batch/8 | 1.48 |
| verify_blob_kzg_proof_batch/16 | 1.41 |
| verify_blob_kzg_proof_batch/32 | 1.49 |
| verify_blob_kzg_proof_batch/64 | 1.37 |

**Comment by sauliusgrigaitis** [comment]
Great work! But this is still significantly slower than `blst_from_scratch` ?

**Comment by belijzajac** [comment]
Yes, and blst-from-scratch is using the pippenger's algorithm

**Pull request closed without merging**
