### PR TITLE
Handle EIP4844 proving when challenge is in domain

### PR DESCRIPTION
**Pull request by dariolina**
Issue: `compute_kzg_proof_rust` was hanging for me when `x` was a power of root of unity, which is a common case when KZG is used as vector commitment (like we do at Subspace).
Fix:
- Handled the case when x is inside the evaluation domain (is a power of root of unity) according to what Ethereum does in [PR111](https://github.com/ethereum/c-kzg-4844/pull/111) by setting its inverse to 1
- Fix infinite loops due to missing increments in the same case
- Added test
cc @nazar-pc

### CODE REVIEW

**Comment by sauliusgrigaitis** [comment]
Thanks @dariolina, let's wait for CI, this should fail for other ECC backends that run EIP-4844 tests.

**Comment by belijzajac** [comment]
These changes are no longer relevant because with #199 I remove all previous EIP-4844 tests and add 9 new ones, together with an entirely rewritten EIP-4844 interface up to commit [53b38fa](https://github.com/ethereum/c-kzg-4844/tree/53b38face021d3c60d6d8d14ce3e92989cfea45a), which include your proposed changes.

**Comment by sauliusgrigaitis** [comment]
Thanks @belijzajac, I think we should get #199 merged and try to avoid large and long-running PR in the future.

**Comment by dariolina** [comment]
Great, it would be nice to have it working. I'll use the fork in the meantime.

**Comment by sauliusgrigaitis** [comment]
Closing in favor of #199

**Pull request closed without merging**
