### PR TITLE
Wasm support

### PR DESCRIPTION
**Pull request by nazar-pc**
Initially my goal was to make it `no_std` compatible and it almost is, but `blst` isn't (see https://github.com/supranational/blst/pull/150), without that it still compiles for `wasm32-unknown-unknown` target, but wouldn't work for target that doesn't have standard library at all.

I'll send a PR with full `no_std` support once https://github.com/supranational/blst/pull/150 or similar is upstreamed.

Wasm is skipped in CI on macOS because it needs proper Clang with wasm support and not the default Apple's contraption. But it didn't seem worthwhile to add LLVM installation on top since if it works on Linux and Windows, it'll work the same exact way on macOS too given compiler support.

### CODE REVIEW

**Comment by sauliusgrigaitis** [comment]
Thanks @nazar-pc ! However, I don't think we should exclude `eip-4844` module from Wasm support. I really would like to avoid this patchy dolly approach. Is there something unsolvable for `eip-4844` to support Wasm?

**Comment by nazar-pc** [comment]
`eip-4844` turned out to be a bit more involved, for instance it uses file system access for `load_trusted_setup_file*`. It is certainly still possible to expose most of the stuff, but I wasn't interested in it so decided to make it optional.

Should I expose all the APIs that are possible as is and remove optional `eip-4844` feature?

**Comment by nazar-pc** [comment]
Done

**Comment by sauliusgrigaitis** [comment]
@belijzajac could you double-check and merge?

**Pull request merged**
