### PR TITLE
Bump C_KZG_4844_GIT_HASH

### PR DESCRIPTION
**Pull request by ArtiomTr**
In this PR:
* Update `C_KZG_4844_GIT_HASH` to latest c-kzg-4844 commit ([`5115420`](https://github.com/ethereum/c-kzg-4844/tree/5115420ba3f919f5501155ba18633667001b6a07))
* Added support for nim bindings

### CODE REVIEW

**Comment by sauliusgrigaitis** [comment]
Ok, so this is a funny - there is some [issue](https://github.com/sifraitech/rust-kzg/actions/runs/7654377297/job/20858247871) when `constantine` in `rust-kzg` is called using Nim bindings. I think it's very rare use case, especially when `rust-kzg` has performance penalty for `constantine`. @mratsim let us know if you see a quick fix for this. If not, then we will just not support this case and will refer Nim users to use `constantine` directly.

**Comment by mratsim** [comment]
It's multiple definitions of some Nim primitives.



b-4c3e-bc22-c691f8a29fed)



There is a workaround iirc but have to check and try myself (on mobile)

**Comment by mratsim** [comment]
To ensure there is no naming conflict, Nim core functions can be exported to a RTL (Runtime Library) file: https://nim-lang.org/nimc.html#dll-generation

I think Constantine itself might be RTL-free as I purposely avoided all dependencies on Nim stdlib but I might have missed something or use convenient types like `seq` for high-level non-hotpath non-cryptographic-secret code.

In the meantime I think it's reasonable to point to Constantine directly.

**Comment by sauliusgrigaitis** [comment]
Thanks for information @mratsim . Let's close it for now and reopen of this if this rare use-case will be hit.

**Pull request merged**
