### PR TITLE
Update to c-kzg-4844 upstream

### PR DESCRIPTION
**Pull request by belijzajac**
This PR updates the interface following the c-kzg-4844 changes.

* Update c-kzg-4844 git hash to [1493f2b](https://github.com/ethereum/c-kzg-4844/tree/1493f2bf2fce6b61f654a314a4ba136fd3b7a277)
* Add Go binding
* Hook up C tests from c-kzg-4844
* Benchmarks for the mcl backend
* Refactor and clean up code

### CODE REVIEW

**Comment by nazar-pc** [comment]
Is there anything in particular left to be done in this PR before landing into `main`?

**Comment by belijzajac** [comment]
Basically these three points:

* Update the c-kzg-4844 git hash that is now 3 weeks old
* Update blst-from-scratch and mcl implementations following the c-kzg-4844 changes
* Make zkcryto and arkworks eip-4844 compliant (these can be lengthy processes that can be done by separate PRs)

**Comment by sauliusgrigaitis** [comment]
I think `zkcrypto` and `arkworks` can wait, even `mcl` can wait if it takes too long.

**Comment by belijzajac** [comment]
This is the last version that supports aggregate KZG proofs.

The 6 functions that made into proposal (https://github.com/ethereum/consensus-specs/pull/3274#issue-1599860911) require us to rewrite a significant amount of logic (commits: https://github.com/sifraitech/rust-kzg/commit/c9e7b658ba333201f0b55bc9486f23e65e871476, https://github.com/sifraitech/rust-kzg/commit/aee67f6928f8d104c96bd0f962c06ecec85c9988, https://github.com/sifraitech/rust-kzg/commit/48c3cb5eb46972845add981d0de30e3cc0889e81; CI: [jobs/7632143695](https://github.com/sifraitech/rust-kzg/actions/runs/4364494274/jobs/7632143695) and [jobs/7631881052](https://github.com/sifraitech/rust-kzg/actions/runs/4364494288/jobs/7631881052)), effectively deprecating the majority of 4844 tests and benchmarks.

**Pull request merged**
