### PR TITLE
Parallelize batched blob kzg proof verification

### PR DESCRIPTION
**Pull request by belijzajac**
Below are the local benchmark results for `blst-from-scratch`:

| Benchmark | Old | New | Speedup |
|--------|--------|--------|--------|
| verify_blob_kzg_proof_batch/1   | 2.8333 ms | 2.8358 ms | 0.99x |
| verify_blob_kzg_proof_batch/2   | 4.6755 ms | 3.1930 ms | 1.46x |
| verify_blob_kzg_proof_batch/4   | 8.5825 ms | 3.2869 ms | 2.61x |
| verify_blob_kzg_proof_batch/8   | 15.849 ms | 6.2911 ms | 2.51x |
| verify_blob_kzg_proof_batch/16 | 29.943 ms | 12.389 ms | 2.41x |
| verify_blob_kzg_proof_batch/32 | 55.501 ms | 24.513 ms | 2.26x |
| verify_blob_kzg_proof_batch/64 | 108.27 ms | 48.739 ms | 2.22x |

Other implementations should yield similar results.

### CODE REVIEW

**Comment by sauliusgrigaitis** [comment]
Great work @belijzajac !

We need to try one more trick. IIRC we talked about this already during the call IIRC. If the number of blobs is higher than physical cores, then blobs should be split into groups and each individual group should run the batched algorithm (the one that c-kzg-4844 runs). For example, if there is 64 blobs and 4 cores, then there will be 4 groups 16 blobs each. Then each group runs on its own core. This should give a significant performance boost, especially for groups with more blobs.

You can get the number of physical cores by using [this](https://docs.rs/num_cpus/latest/num_cpus/fn.get_physical.html). You can also try to benchmark what happens if you split by logical cores. It should work slower.

**Comment by belijzajac** [comment]
So, I patched the `verify_kzg_proof_batch` test locally by changing the blobs count to an uneven number, specifically 47, also added a log printing right above the `blob_group.par_iter()` to see if the blobs splitting actually works, which indeed does:

<details><summary>Details</summary>
<p>

Screenshot_20230417_150008

</p>
</details> 

And here are the local results:

| Benchmark | Old parallel | New parallel | Change |
|--------|--------|--------|--------|
| verify_blob_kzg_proof_batch/1   | 2.8333 ms | 2.8358 ms | +0.87% |
| verify_blob_kzg_proof_batch/2   | 4.6755 ms | 3.1930 ms | +1.34% |
| verify_blob_kzg_proof_batch/4   | 8.5825 ms | 3.2869 ms | +3.02% |
| verify_blob_kzg_proof_batch/8   | 15.849 ms | 6.2911 ms | +2.25% |
| verify_blob_kzg_proof_batch/16 | 29.943 ms | 12.389 ms | +2.16% |
| verify_blob_kzg_proof_batch/32 | 55.501 ms | 24.513 ms | +1.45% |
| verify_blob_kzg_proof_batch/64 | 108.27 ms | 48.739 ms | +0.89% |

This could be just a noise within benchmarks; however, I also replaced `map` to `all` method calls from the iterator trait because I found this in the documentation:

```text
all() is short-circuiting; in other words, it will stop processing as soon as it finds
a false, given that no matter what else happens, the result will also be false.
```

which guarantees an early exit if a single blob in the blob group is guaranteed to have an invalid proof. If we constructed a 4 blob groups containing 16 proofs each (64 blobs / 4 cores = 16 blobs and proofs) that evaluate to either true or false, as such:

```text
blob_group_1 [true, false, ...]
blob_group_2 [false, ...]
blob_group_3 [false, ...]
blob_group_4 [false, ...]
```

that would cost a total of 4 blob verification function calls!

This behavior is not shown in benchmarks because all the proofs generated in them are correct.

**Comment by sauliusgrigaitis** [comment]
For every group you need to call `verify_kzg_proof_batch` and pass the entire group. Again, let's say we have 2 cores and 4 blobs. This means on the first core there will be a single call to `verify_kzg_proof_batch` with blobs 0 and 1 passed, on the second core there will be a single `verify_kzg_proof_batch` call with blobs 2 and 3 passed.

Thanks not how it's currently implemented.

**Comment by belijzajac** [comment]
Comparison between current changes and the first commit:

| Benchmark | Old parallel (first commit) | New parallel (current commit) | Change |
|--------|--------|--------|--------|
| verify_blob_kzg_proof_batch/1   | 2.8203 ms | 2.8484 ms | +0.99%     |
| verify_blob_kzg_proof_batch/2   | 3.1175 ms | 4.7563 ms | **+52.56%** |
| verify_blob_kzg_proof_batch/4   | 3.2755 ms | 8.7011 ms | **+165.64%** |
| verify_blob_kzg_proof_batch/8   | 6.3278 ms | 5.3449 ms | -15.53%    |
| verify_blob_kzg_proof_batch/16 | 12.421 ms | 9.6115 ms | -22.61%    |
| verify_blob_kzg_proof_batch/32 | 24.551 ms | 17.584 ms | -28.37%    |
| verify_blob_kzg_proof_batch/64 | 48.766 ms | 33.336 ms | -31.64%    |

@sauliusgrigaitis should I include the parallel logic from the first commit when `num_blobs < num_cores`, taking into consideration that there doesn't exist such a cpu with 64 physical cores?

**Comment by belijzajac** [comment]
Comparison between current changes and the first commit:

| Benchmark | Old parallel (first commit) | New parallel (current commit) | Change |
|--------|--------|--------|--------|
| verify_blob_kzg_proof_batch/1   | 2.8358 ms | 2.8278 ms | -0.28%     |
| verify_blob_kzg_proof_batch/2   | 3.1478 ms | 3.2810 ms | **+4.23%** |
| verify_blob_kzg_proof_batch/4   | 3.2358 ms | 3.3705 ms | **+4.16%** |
| verify_blob_kzg_proof_batch/8   | 6.3014 ms | 5.3351 ms | - 15.33%    |
| verify_blob_kzg_proof_batch/16 | 12.327 ms | 9.6011 ms | -22.11%    |
| verify_blob_kzg_proof_batch/32 | 24.448 ms | 17.560 ms | -28.17%    |
| verify_blob_kzg_proof_batch/64 | 48.769 ms | 33.250 ms | -31.82%    |

**Comment by sauliusgrigaitis** [comment]
Great work @belijzajac . Slight degrade for 2 and 4 blobs is probably just a random?

**Comment by belijzajac** [comment]
I hope so, this is what I'm seeing in the CI benchmarks:

<details><summary>Details</summary>
<p>

Screenshot_20230418_154643

</p>
</details>

**Pull request merged**
