### PR TITLE
Compilation fixes and change to workspace

### PR DESCRIPTION
**Pull request by nazar-pc**
I was trying to use this as git dependency and hit numerous issues.

This PR fixes many of the issues and allows to use arkworks implementation as dependency, but ckzg at least still fails to link openmp (in Rust, static library builds successfully).

Sed on my Ubuntu 22.04 (upgraded from older release back to 13.10 I believe, pre-unified usr) has sed at `/bin/sed`, so I had to remove full path there as unnecessary.

### CODE REVIEW

**Comment by sauliusgrigaitis** [comment]
Hey @nazar-pc, great work! Could you fix the build as seems it doesn't pass the github workflows.

**Comment by nazar-pc** [comment]
It doesn't seem to even start, not sure why (I just rebased on top of `update_upstream`, so it should work). Maybe you need to trigger it manually since I'm not a collaborator?

**Comment by sauliusgrigaitis** [comment]
You should be able to run the debug the build on your own [fork]( https://github.com/subspace/rust-kzg/actions/runs/4295233370/jobs/7485361637) of the repo.

**Comment by nazar-pc** [comment]
Those are clippy errors and do not seem to be directly related to the changes I did. Locally it fails for me both with and without these changes.

Do you still want me to pursue that? Changes will be much more significant if I do that.

**Comment by sauliusgrigaitis** [comment]
You can wait a bit and see that https://github.com/sifraitech/rust-kzg/pull/191 passes. Clippy often complains after Rust version update, so this could be the case.

In any case, in order to accept the PR the build needs to pass.

**Comment by nazar-pc** [comment]
It passes, but at the same time it clearly doesn't actually run Clippy properly because with this PR and same version Clippy finds a bunch of issues in the code that didn't change.

**Comment by nazar-pc** [comment]
Fixed everything, now CI passes and this should be ready for review again.

BTW CI can be greatly simplified, for instance `cargo clippy --workspace --all-targets` is sufficient to check everything at once.

**Comment by sauliusgrigaitis** [comment]
Thanks @nazar-pc !

@belijzajac could you double check it as this is  based on your branch?

**Comment by belijzajac** [comment]
Should we hold off until more commits are added, like https://github.com/subspace/rust-kzg/commit/66de335ae1379db414f7a04670df716ffe817f99 that you're still working on, or should we merge now?

**Comment by nazar-pc** [comment]
That commit will be a separate independent PR, this one already includes everything I wanted to include. This one is solely focused on making this repo usable as git dependency for others.

**Pull request merged**
